import {
  EmitContext,
  emitFile,
  listServices,
  getNamespaceFullName,
  navigateTypesInNamespace,
  Model,
  Namespace,
  Interface,
  Program,
  Type,
  Scalar,
} from "@typespec/compiler";

export type EmitterOptions = {
  "emitter-output-dir": string;
};

interface FieldInfo {
  name: string;
  type: Type;
  optional: boolean;
}

interface ServiceInfo {
  namespace: Namespace;
  iface: Interface;
  serviceName: string;
  serviceFQN: string;
  models: Model[];
}

function extractFields(model: Model): FieldInfo[] {
  const fields: FieldInfo[] = [];
  for (const [name, prop] of model.properties) {
    fields.push({ name, type: prop.type, optional: prop.optional ?? false });
  }
  return fields;
}

function isStringType(type: Type): boolean {
  if (type.kind === "Scalar") return (type as Scalar).name === "string";
  if (type.kind === "Intrinsic") return (type as any).name === "string";
  return false;
}

function isIntType(type: Type): boolean {
  if (type.kind === "Scalar") {
    const n = (type as Scalar).name;
    return ["int8","int16","int32","int64","uint8","uint16","uint32","uint64","integer"].includes(n);
  }
  return false;
}

function isFloatType(type: Type): boolean {
  if (type.kind === "Scalar") {
    const n = (type as Scalar).name;
    return ["float","float32","float64","decimal"].includes(n);
  }
  return false;
}

function isBoolType(type: Type): boolean {
  if (type.kind === "Scalar") return (type as Scalar).name === "boolean";
  return false;
}

function isArrayType(type: Type): boolean {
  return type.kind === "Model" && !!(type as Model).indexer;
}

function arrayElementType(type: Type): Type {
  if (type.kind === "Model" && (type as Model).indexer) return (type as Model).indexer!.value;
  return type;
}

function typeToGo(type: Type): string {
  if (isStringType(type)) return "string";
  if (isIntType(type)) return "int64";
  if (isFloatType(type)) return "float64";
  if (isBoolType(type)) return "bool";
  if (isArrayType(type)) return `[]${typeToGo(arrayElementType(type))}`;
  if (type.kind === "Model") return type.name || "any";
  return "any";
}

function collectServices(program: Program): ServiceInfo[] {
  const services = listServices(program);
  const result: ServiceInfo[] = [];
  function collectFromNs(ns: Namespace) {
    for (const [,iface] of ns.interfaces) {
      const nsFQN = getNamespaceFullName(ns);
      const models: Model[] = [];
      const seen = new Set<string>();
      navigateTypesInNamespace(ns, { model: (m: Model) => { if (m.name && !seen.has(m.name)) { models.push(m); seen.add(m.name); } } });
      result.push({ namespace: ns, iface, serviceName: iface.name, serviceFQN: `${nsFQN}.${iface.name}`, models });
    }
  }
  for (const svc of services) collectFromNs(svc.type);
  if (result.length === 0) {
    const globalNs = program.getGlobalNamespaceType();
    for (const [, ns] of globalNs.namespaces) collectFromNs(ns);
    collectFromNs(globalNs);
  }
  return result;
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const program = context.program;
  const outputDir = context.emitterOutputDir;
  const services = collectServices(program);
  for (const svc of services) {
    const snake = (s: string) => s.replace(/([A-Z])/g, (m, c, i) => (i ? "_" : "") + c.toLowerCase());
    const pkg = `specodec_${snake(svc.namespace.name?.toLowerCase() ?? "svc")}`;
    const lines: string[] = [];
    lines.push("// Generated by @specodec/typespec-specodec-go. DO NOT EDIT.");
    lines.push(`package ${pkg}`);
    lines.push("import \"github.com/specodec/specodec-go\"");
    lines.push("");
    for (const m of svc.models) {
      if (!m.name) continue;
      const fields = extractFields(m);
      lines.push(`type ${m.name} struct {`);
      for (const f of fields) {
        const goName = f.name.charAt(0).toUpperCase() + f.name.slice(1);
        lines.push(`\t${goName} ${typeToGo(f.type)} \`json:"${f.name}${f.optional ? ",omitempty" : ""}"\``);
      }
      lines.push("}");
      lines.push("");
    }
    const fileName = snake(svc.serviceName) + "_types.go";
    await emitFile(program, { path: `${outputDir}/${fileName}`, content: lines.join("\n") });
  }
}
